name: Elijah's Webpage
description: Blogs, Astro and more...

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: kramdown
#redcarpet:
#  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

#url: http://nadjetey.github.io/wangana
permalink: /posts/:categories/:year/:month/:day/:title/

pygments: true

#permalink: /:year/:month/:title/

owner:
    name: Elijah Bernstein-Cooper
    twitter: ebernste1
    github: ezbc
    bitbucket: ezbc
    disqus_shortname: ezbc

ga_id: #
ga_username: #
twitter: ebernste1
gravatar_url: http://www.r2d2.uwm.edu/images/uw-madison-logo.gif
timezone: Central
